### ISSUE TITLE
Sound problems on Raspberry Pi 2 

### ISSUE THREAD

**Issue by inspector71** [xbmc-catchuptv-au/repo#14] opened 2015-06-01 09:15 UTC
Hi

Thanks for this work, it's sensational. Unfortunately I'm having trouble with sound. It worked a week or two ago when I first found this brilliant add-on but now audio is either silent or just a tiny bit of audio can be heard very briefly and then nothing.

The problematic content is the footy video.

I'm using a Raspberry Pi 2 running Kodi 14.2 (Helix, Git:`7cc53a9`) via OpenELEC 5.0.8. 

Sound setup is fairly simple: HDMI output to a TV with the following capabilities:

> `OpenELEC:~ # tvservice -a`
>     `PCM supported: Max channels: 2, Max samplerate:  48kHz, Max samplesize 24 bits.`
>     `AC3 supported: Max channels: 6, Max samplerate:  48kHz, Max rate  640 kb/s.`

Ignore the AC3 capability as I don't use that. Kodi only outputs 2.0 channels. Very simple.

Of course there's more audio settings I could detail if you need any more info. 

Since Kodi hasn't changed, is it possible something in the footy streams have changed that the this excellent add-on (or a dependency) may need to be adjusted to cater for?

The standard log (debugging off) looks ok:

http://pastebin.com/fW8u0TW5

Appreciate your superb hard work. Happy to supply any other info you might want if it helps.

**Comment by andybotting** [comment] 2015-06-01 23:41
It's possible that the audio stream has changed, but there isn't anything we can do in the plugin to help here. The plugin just pulls the video URL and sends it to Kodi to play - so nothing fancy going on.

Having said that, I can't reproduce the issue on either of my Rpi 1 or 2 and my LG TV.

**Comment by inspector71** [comment] 2015-06-02 04:45
Thanks Andy
It's all rather mysterious. Cool that you're a Pi fan as well :)
I'll dig deeper into the issue soon as I have some time. 
FWIW my test unit in this case has been a relatively old Sony Bravia however I also have an LG TV.
After I get the debugging info whilst keeping the test environment consistent with the Sony, I'll try the LG I think.
Thanks for your feedback and again, super effort getting and keeping this add-on rocking and rolling!
Hope to get more information within the next couple of days.
Would be great if they had streams in 5.1 surround so I could turn off the commentary channel when they get too annoying but for the time being I'll be more than happy to just have the 2.0 channels working as simplistically as possible.
One note, would it be possible for you to detail more of your Kodi-on-Pi setup? Distro, Kodi version, audio section of the settings.xml file? (don't remember the proper name of it right now).

**Comment by andybotting** [comment] 2015-06-02 05:27
Sure! I'm just running a super plain OpenELEC install, with Helix atm. 

I've not configured anything special for the audio at all. I've only got a 2.1 setup here, so it's been perfect from the start.

It would be super to be able to turn off the commentary sometimes. We don't actually have a lot of options here - the stream we're using is actually meant for the AFL 'Smart Replay' app that you often see on Samsung and LG smart TV's, which is pretty basic.

**Comment by inspector71** [comment] 2015-08-28 18:34
Hi again. Super sorry for the delayed update but there's good news here. A month or few back I found a workaround for this issue. Two settings needs to be tweaked:

Settings -> Kodi -> Videos -> Acceleration -> Allow hardware acceleration (OMXPlayer) 
must be disabled

Settings -> Kodi -> System -> Audio output -> Output configuration 
must be ``Fixed``

The bad news is disabling OMXPlayer hardware acceleration can make Kodi behave a bit laggardly but strangely doesn't effect the quality of AFL Video playback!

It's certainly a PITA to have to toggle the OMXPlayer acceleration every time I want to watch AFL Videos but I leave the Audio output, Output configuration on ``Fixed`` all the time and this isn't a problem for me. That said, I'm not running any high-spec multi-channel funky receiver setup. Just the bog standard speakers built into my Sony Bravia.

I found this solution out there somewhere by searching and I think found a similar forum detailing where the configuration options passed to OMXPlayer for audio is a coded string that isn't all that dynamic or something. Wish I still had the reference. However in the same research session I found plenty of people suggesting OMXPlayer's hardware acceleration wasn't that good. It's potentially more of an issue with how OMXPlayer's hardware acceleration works with the closed-source drivers for the Raspberry Pi's VideoCore h264 block.

I tested this problem with the latest OpenELEC 6, beta 4 (AKA 5.95.4) which uses Kodi 15.1 (Isengard) and really hoped the problem would be somehow fixed. No suck luck.

Looks like whatever the AFL Video streams are doing, some sort of encoding issue almost unique to them, it's not suited to the Raspberry Pi! I smell a conspiracy! Bloody Ross Oakley must be involved I bet! These audio problems simply don't happen with the many other streams I've been watching lately. YouTube is fine and many other streams work fine as well. Should have known couldn't trust anything Telstra's had a poke at :)

**Comment by andybotting** [comment] 2015-08-30 09:17
Thanks for the update.

From memory, I had some weird issues with AFL and an old AppleTV 1 using OpenELEC and the Broadcom CrystalHD decoding card. It would stutter and play up so much that I also had to disable its hardware decoding too.

All signs to point to them doing silly things with their encoding, but it's strange I've not managed to reproduce it on any of rpi systems (1 or 2).

**Comment by inspector71** [comment] 2015-08-30 13:30
Interesting that your previous experience also involved a Broadcom chip as they are of course the core chips in the Raspberry Pi since Eben Upton got the cushy deal with them thanks to working with them.

One option I was wondering about, as I'm not very familiar with Python or Kodi plugins, is if a system preference can be toggled when starting and stopping a plugin. I guess this would be an unfortunate and dubious but perhaps effective workaround. 

In addition I'll see if I can research the issue further and find those references I mentioned.

Also reckon it will be useful to look into the encoding details. Time for some mediainfo probing! But how to probe a stream without saving it via wget or curl? If I do save it, will that change the data and obfuscate the problem? Hmmm, plot thickens, kinda.

**Comment by andybotting** [comment] 2016-05-13 06:01
Going to close this ticket due to age. Any luck with newer OpenELEC? I'm now using LibreELEC on new RPi installs.

**Closed by andybotting** 2016-05-13 06:01 UTC

**Comment by inspector71** [comment] 2016-05-13 08:21
Just started trying LibreELEC myself, although not a clean install but
rather an update over OE 6.0.3

Just played the Banana in Pyjamas no worries so there's either no bug or
it's somehow limited to a different setup/network though the probability of
that is reduced given the two locations both use the same ISP and very
similar modem.

Nevermind. Sorry for the 'noise' in your signal. Thanks for the hard work
you do to make this plugin available. Helps a lot of taxpayers pull and
play content from the nation's public broadcaster that they've indirectly
paid for so should be able to legitimately watch via any popular platform.
